version: '3.8'
services:
  mysql-compose:
    image: mysql:8.0
    restart: always
    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_RANDOM_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_spring_kotlin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local