cors:
  origin_patterns: http://locahost:8080,http://locahost:3000,http://softWalter.com.br,
security:
  jwt:
    token:
      secret-key: 36cr37
      expire-length: 3600000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb;MODE=LEGACY
#    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
spring-doc:
  path-to-math:
    - /auth/singin
    - /cadastro/**
  swagger-iu:
    use-root-path: true