spring:
  main:
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_kotlin?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin1234
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
#      database-platform: org.hibernate.dialect.MySQL5Dialect
#      hibernate:
#        ddl-auto: update
#        dialect: org.hibernate.dialect.MySQL5Dialect
#      properties:
#        hibernate:
#          show_sql: true
#          use_sql_comments: true
#          format_sql: true
