spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_kotlin
    username: root
    password: admin1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
