cors:
  origin_patterns: http://locahost:8080,http://locahost:3000,http://softWalter.com.br,
security:
  jwt:
    token:
      secret-key: 36cr37
      expire-length: 3600000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_kotlin?useTimezone=true$serverTimezone=UTC&createDatabaseIsNotExist=true
    username: root
    password: admin1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
spring-doc:
  path-to-math:
    - /auth/**
    - /cadastro/**
  swagger-iu:
    use-root-path: true