cors:
  origin_patterns: http://localhost:8080,http://localhost:3000,http://softWalter.com.br
file:
  upload-dir: D:/PROJETOSINTELLIJ/uploadImagens
security:
  jwt:
    token:
      secret-key: 36cr37
      expire-length: 3600000
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/rest_spring_kotlin?useTimezone=true$serverTimezone=UTC&createDatabaseIsNotExist=true
    url: jdbc:mysql://localhost:3306/rest_spring_kotlin?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username: root
    password: admin1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  sevlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  path-to-math:
    - /auth/**
    - /cadastro/**
  swagger-iu:
    use-root-path: true