cors:
  origin_patterns: http://locahost:8080,http://locahost:3000,http://softWalter.com.br,
security:
  jwt:
    token:
      secret-key: 36cr37
      expire-length: 3600000
server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
spring-doc:
  path-to-math:
    - /auth/**
    - /cadastro/**
  swagger-iu:
    use-root-path: true